### ISSUE TITLE
Input

### ISSUE THREAD

**Issue by 5putnik** [thaynamorim/discreta03g01#4]
O código de input do programa deve estar funcionando, ou seja, o programa deve estar apto a ler o arquivo de texto quando o programa for rodado ./ex3.x < input.txt

**Comment by pvpatriota** [comment]
Ok!
Irei começar os testes de entrada do simulador hoje a noite. 
Logo mais estará na função o protótipo da entrada de dados pra executar os testes iniciais.

**Comment by 5putnik** [comment]
Lembrando que pra rodar o código com um arquivo de entrada é ./ex3.c < nomedoarquivo.txt ;)

**Comment by pvpatriota** [comment]
Perfeito!
O arquivo que vai conter as entradas será do tipo .txt? 
Ou seria válido criar um arquivo .c na execução dos testes?

**Comment by 5putnik** [comment]
Será txt mesmo. O importante é só ter os números, ser um texto sem formatação, sabe?

**Comment by pvpatriota** [comment]
Ta certo.
A ordem que iremos seguir, foi a definida do quadro pelo professor, correto?

**Comment by mateuslenier** [comment]
Hugo terminamos o código de entrada mas utilizamos uma forma diferente de leitura do arquivo entrada.txt.

**Comment by 5putnik** [comment]
Bom, eu ia falar pra trocar o fscanf() pelo scanf(), mas vocês já fizeram isso antes de eu falar. Ótimo, problema resolvido. :+1:
