### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by 5putnik** [thaynamorim/discreta03g01#5]
O programa deve estar com PELO MENOS 3 níveis de output:
0 - SÓ O NECESSÁRIO
1 - Run mais detalhado
2 - Extremamente detalhado / programador rodando pra debugar

Entre o 1 e o 2 seria legal ter mais níveis, mas não é necessário.

(no código eu coloquei if(DEBUG>4) pra umas funções internas pra ser modificado depois pro último nível de debug que for setado. Ex: foram criados 4 níveis de output, então coloca if(DEBUG>2) )

**Comment by pvpatriota** [comment]
Seria legal tanto pra o output como para o input, receber as entradas de arquivos do tipo nomedoarquivo.c, usando com a finalidade de testes.
Após realizar todos os testes, as entradas e saídas seriam modificadas para arquivos do tipo .txt

**Comment by thaynamorim** [comment]
O output já existe um arquivo chamado saida.c que serve só pra imprimir as saídas com o debug, por enquanto, pra gente ter uma ideia.

**Comment by thaynamorim** [comment]
Inclusive, eu e Canejo colocamos os níveis 0 e 1 já.

**Comment by pvpatriota** [comment]
Beleza Thayna. Eu tava dando uma conferida aqui.

**Comment by thaynamorim** [comment]
Níveis de DEBUG resolvidos e feitos.
