### ISSUE TITLE
Níveis de DEBUG

### ISSUE THREAD

**Issue by thaynamorim** [thaynamorim/discreta03g01#6]
Desenvolver o que exatamente vamos imprimir no Output com os níveis de Debug. Deem sugestões.

**Comment by canejo12** [comment]
1) Numero de tokens no final
2) Numero de transições disparadas
3) Quantidade de tokens em lugar
4) Numero detokens consumidos e produzidos
5) Quantas vezes disparou a transição

**Comment by canejo12** [comment]
Sugestões implementadas nos niveis de DEBUG.
