### ISSUE TITLE
função entrada com problemas

### ISSUE THREAD

**Issue by pvpatriota** [thaynamorim/discreta03g01#8]
Os bugs na hora de compilar o arquivo já foram resolvidos, mas a função entrada ainda não está lendo o arquivo txt como deveria.

**Comment by mateuslenier** [comment]
Paulo, verifiquei alguns arquivos ontem e percebi que esta faltando a inicialização na função main,para que ocorra a leitura do arquivo entrada.txt.

**Comment by pvpatriota** [comment]
É preciso corrigir esse problema para que o programa faça a leitura correta do arquivo.txt

**Comment by mateuslenier** [comment]
Corrigido todos os bugs reportados. Função funcionando 100%.
